name: Publish
On:
  push:
    branches:
      -main
  release:
    types: [published]
jobs:
  publish-image:
    runs-on: ubuntu-latest
    permissions:
      content: read
      package : write
    steps:
    - name: Checkout
      uses: action/checkout@v4
    - name: Doctor Meta
      id: meta
      uses: doctor/meta-action@v5
      with:
        images: ghcr.io/bintangaugryf/belajar-ci-id
        tags: latest
    - name: login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: lint-dockerfile
      uses: hadolint/hadolint-action@3.1.0
      with:
        dockerfile: Dockerfile
    - name :  Build Container
      uses: docker/build-push-action@v5
      with:
        context: -
        push: true
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ steps.meta.outputs.labels }},  ghcr.io/bintangaugryf/belajar-ci-id:latest
        
